apiVersion: v1
kind: Service
metadata:
  name: push-server
  namespace: push-notifications
spec:
  selector:
    app: push-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP