apiVersion: v1
kind: Service
metadata:
  name: push-client
  namespace: push-notifications
spec:
  selector:
    app: push-client
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
  type: NodePort