# 서버 설정
server:
  port: 8080  # 서버가 실행될 포트

# Redis 설정
redis:
  host: "localhost"     # Redis 호스트 주소
  port: 6379            # Redis 포트 번호
  password: ""          # Redis 비밀번호 (설정하지 않은 경우 비워두기)

# MySQL 설정
mysql:
  host: "localhost"     # MySQL 호스트 주소
  port: 3306            # MySQL 포트 번호
  user: "root"          # MySQL 사용자명
  password: "password"  # MySQL 비밀번호
  database: "push_notification_db"   # 사용할 데이터베이스 이름